{
 "title": "Postgres Overview",
 "tags": [ "postgres" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Consumo vs Generacion Hoy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT date, generation, consumption FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Atardecer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT sunset FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Amanecer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT sunrise FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Ratio de Autoconsumo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT generation, consumption FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Viento",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT wind_speed, wind_direction FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Clima Actual",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT date, clouds, humidity, rain, pressure, snow, temperature, wind_direction, wind_speed FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Potencia Neta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT date, consumption, generation FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Relacion Consumo-Temperatura",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT temperature, consumption FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Consumo vs Generacion Actual",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT SUM(consumption) AS \"Consumo Total\" FROM energy_snapshots GROUP BY date LIMIT 50 "
    },
    {
     "dataset": "electricsim",
     "rawSql": "SELECT SUM(generation) AS \"Generacion Total\" FROM energy_snapshots GROUP BY date LIMIT 50 "
    }
   ]
  },
  {
   "title": "Relacion Generacion-Nubes",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT clouds, generation FROM energy_snapshots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Relacion Generacion-Velocidad_Viento",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "electricsim",
     "rawSql": "SELECT wind_speed, generation FROM energy_snapshots LIMIT 50 "
    }
   ]
  }
 ]
}